on:
  workflow_dispatch:
    inputs:
      format:
        description: Output video format to render
        required: true
        type: choice
        options:
          - mp4
          - gif
      name:
        description: Video name to render
        required: true
        type: choice
        options:
          - hello

name: Render
jobs:
  render:
    name: Render - ${{ inputs.name }}.${{ inputs.format }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Node.js dependencies
        run: npm ci
      - name: Render
        run: npm run render:${{ inputs.format }} --video=${{ inputs.name }}
      - name: Upload rendered video artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out
